name: "Argus Code Review"
description: "AI-powered PR review using Cursor agent. Posts review comments on pull requests."
author: "sasa-tomic"

branding:
  icon: "eye"
  color: "purple"

inputs:
  cursor-api-key:
    description: "Cursor API key (from https://cursor.com/dashboard?tab=integrations)"
    required: true
  github-token:
    description: "GitHub token for API access (defaults to github.token)"
    required: false
    default: ${{ github.token }}
  model:
    description: "Cursor model to use"
    required: false
    default: "sonnet-4.5-thinking"
  prompt-file:
    description: "Path to custom prompt file (relative to repo root). If not provided, uses built-in default."
    required: false
    default: ""
  skip-label:
    description: "Label name that skips AI review when present on the PR"
    required: false
    default: "skip-ai-review"

runs:
  using: "composite"
  steps:
    - name: Check skip label
      id: check-skip
      shell: bash
      env:
        SKIP_LABEL: ${{ inputs.skip-label }}
        PR_LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}
      run: |
        set -eEuo pipefail
        if echo "$PR_LABELS" | grep -q "\"$SKIP_LABEL\""; then
          echo "skip=true" >> "$GITHUB_OUTPUT"
          echo "Skipping AI review: '$SKIP_LABEL' label present"
        else
          echo "skip=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Validate API key
      if: steps.check-skip.outputs.skip != 'true'
      shell: bash
      env:
        CURSOR_API_KEY: ${{ inputs.cursor-api-key }}
      run: |
        set -eEuo pipefail
        if [ -z "$CURSOR_API_KEY" ]; then
          echo "ERROR: cursor-api-key input not provided"
          exit 1
        fi

    - name: Setup Node.js
      if: steps.check-skip.outputs.skip != 'true'
      uses: actions/setup-node@v4
      with:
        node-version: "22"

    - name: Install dependencies
      if: steps.check-skip.outputs.skip != 'true'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        set -eEuo pipefail
        npm ci --prefer-offline --no-audit

    - name: Install Cursor CLI
      if: steps.check-skip.outputs.skip != 'true'
      shell: bash
      run: |
        set -eEuo pipefail

        INSTALLER=$(mktemp)
        curl -fsSL https://cursor.com/install -o "$INSTALLER"

        if ! head -1 "$INSTALLER" | grep -q '^#!.*bash'; then
          echo "ERROR: Downloaded file is not a bash script"
          rm -f "$INSTALLER"
          exit 1
        fi

        bash "$INSTALLER"
        rm -f "$INSTALLER"

        echo "$HOME/.cursor/bin" >> "$GITHUB_PATH"

    - name: Generate PR data
      if: steps.check-skip.outputs.skip != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        set -eEuo pipefail

        npx tsx "${{ github.action_path }}/scripts/prepare-pr-review.ts" \
          ${{ github.event.pull_request.number }} \
          --output pr_data.md

    - name: Prepare prompt
      if: steps.check-skip.outputs.skip != 'true'
      id: prompt
      shell: bash
      env:
        CUSTOM_PROMPT: ${{ inputs.prompt-file }}
      run: |
        set -eEuo pipefail

        if [ -n "$CUSTOM_PROMPT" ] && [ -f "$CUSTOM_PROMPT" ]; then
          echo "Using custom prompt: $CUSTOM_PROMPT"
          cat "$CUSTOM_PROMPT" pr_data.md > review_prompt.md
        else
          echo "Using default prompt"
          cat "${{ github.action_path }}/prompts/default.md" pr_data.md > review_prompt.md
        fi

    - name: Run AI review
      if: steps.check-skip.outputs.skip != 'true'
      id: ai-review
      shell: bash
      continue-on-error: true
      env:
        CURSOR_API_KEY: ${{ inputs.cursor-api-key }}
        MODEL: ${{ inputs.model }}
      run: |
        set -eEuo pipefail

        if ! cursor-agent --model "$MODEL" \
          -p "$(cat review_prompt.md)" > ai_review_output.md 2>&1; then
          echo "ERROR: cursor-agent failed" | tee ai_review_output.md
          echo "approve=error" >> "$GITHUB_OUTPUT"
          exit 1
        fi

        cat ai_review_output.md

        if [ ! -s ai_review_output.md ]; then
          echo "ERROR: No review output generated" | tee ai_review_output.md
          echo "approve=error" >> "$GITHUB_OUTPUT"
          exit 1
        fi

        # Determine approval status
        if grep -E '^\*\*Decision\*\*:' ai_review_output.md | grep -qi 'APPROVE' && \
           ! grep -E '^\*\*Decision\*\*:' ai_review_output.md | grep -qi 'REQUEST_CHANGES'; then
          echo "approve=true" >> "$GITHUB_OUTPUT"
          echo "AI recommends APPROVAL"
        elif grep -E '^\*\*Decision\*\*:' ai_review_output.md | grep -qi 'REQUEST_CHANGES'; then
          echo "approve=false" >> "$GITHUB_OUTPUT"
          echo "AI recommends REQUEST_CHANGES"
        else
          echo "approve=unknown" >> "$GITHUB_OUTPUT"
          echo "AI decision could not be determined"
        fi

    - name: Handle AI review failure
      if: steps.check-skip.outputs.skip != 'true' && steps.ai-review.outcome == 'failure'
      shell: bash
      run: |
        set -eEuo pipefail

        cat > ai_review_output.md <<'EOF'
        ## âš ï¸ AI Review Failed

        The AI review could not be completed. This may be due to:
        - Cursor API service issues
        - Network connectivity problems
        - Rate limiting
        - Invalid API key

        Please proceed with manual code review.
        EOF

    - name: Find existing AI review comment
      if: steps.check-skip.outputs.skip != 'true'
      id: find-comment
      uses: peter-evans/find-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: "<!-- ai-pr-review -->"

    - name: Prepare review comment
      if: steps.check-skip.outputs.skip != 'true'
      id: prep-comment
      shell: bash
      env:
        APPROVE_STATUS: ${{ steps.ai-review.outputs.approve }}
      run: |
        set -eEuo pipefail

        REVIEW_LINES=$(wc -l < ai_review_output.md)

        cat > comment_body.md <<'EOF'
        <!-- ai-pr-review -->
        # ðŸ¤– AI Code Review

        EOF

        if [ "$APPROVE_STATUS" = "true" ]; then
          echo "**ðŸ‘ APPROVED**" >> comment_body.md
        elif [ "$APPROVE_STATUS" = "false" ]; then
          echo "**ðŸ‘Ž CHANGES REQUESTED**" >> comment_body.md
        else
          echo "**â“ REVIEW ERROR**" >> comment_body.md
        fi

        echo "" >> comment_body.md

        if [ "$REVIEW_LINES" -gt 150 ]; then
          echo "<details>" >> comment_body.md
          echo "<summary>ðŸ‘€ View Full Review (${REVIEW_LINES} lines)</summary>" >> comment_body.md
          echo "" >> comment_body.md
          cat ai_review_output.md >> comment_body.md
          echo "" >> comment_body.md
          echo "</details>" >> comment_body.md
        else
          cat ai_review_output.md >> comment_body.md
        fi

        echo "" >> comment_body.md
        echo "---" >> comment_body.md
        echo "*Generated for commit: ${{ github.event.pull_request.head.sha }}*" >> comment_body.md

        {
          echo 'comment_body<<EOF_COMMENT_BODY'
          cat comment_body.md
          echo 'EOF_COMMENT_BODY'
        } >> "$GITHUB_OUTPUT"

    - name: Post or update AI review comment
      if: steps.check-skip.outputs.skip != 'true'
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        edit-mode: replace
        body: ${{ steps.prep-comment.outputs.comment_body }}

outputs:
  decision:
    description: "AI review decision: true (approve), false (request changes), unknown, or error"
    value: ${{ steps.ai-review.outputs.approve }}
